version: '3.9'
services:
  backend:
    build:
      context: ./server
    ports:
      - "5000:5000"
    depends_on:
      - db

  frontend:
    build:
      context: ./client3
    ports:
      - "3000:3000"
    depends_on:
      - backend

  db:
    image: postgres:15
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: taskmanagement
    ports:
      - "5432:5432"
