"use client"
/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/pECY5TwqeAg
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
**/

import Link from "next/link"
import { useRouter } from "next/navigation";

export default function front() {
  const router = useRouter();

  return (
    <div className="flex min-h-[100dvh] flex-col items-center justify-center bg-background px-4 py-12 sm:px-6 lg:px-8">
      <div className="mx-auto max-w-md space-y-6 text-center">
        <h1 className="text-3xl font-bold tracking-tighter text-foreground sm:text-4xl">Welcome to Task manager</h1>
        <p className="text-muted-foreground">Create and Manage Tasks</p>
        <div className="flex flex-col gap-4 items-center justify-center sm:flex-row">
          <Link
            href="/loginsignup"
            className="inline-flex h-10 w-full items-center justify-center rounded-md bg-primary px-8 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50 sm:w-auto">
           Login/Signup
          </Link>
        </div>
      </div>
    </div>
  );
}
